services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command:
      ["python3", "main.py", "--host", "0.0.0.0"]
    volumes:
      - app_volume:/usr/src/app

volumes:
  app_volume:
